---
# tasks file for xfce
- name: Install XFCE packages
  apt: name={{ item }} state=present
  with_items:
    - xfce4
    - xfce4-goodies
    - gnome-icon-theme-full
    - tango-icon-theme
    - lightdm

- name: set XFCE as default in lightdm
  command: /usr/lib/lightdm/lightdm-set-defaults --session xfce4-session
